name: ride_sharing_user_app
description: A ride sharing Flutter project.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  intl: ^0.19.0
  shared_preferences: ^2.2.3
  http: ^1.2.1
  connectivity_plus: ^6.0.3
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.1.2
  path_provider: ^2.1.3
  image_picker: ^1.1.2
  country_code_picker: ^3.0.0
  dotted_border: ^2.1.0
  flutter_svg: ^2.0.10+1
  flutter_switch: ^0.3.2
  percent_indicator: ^4.2.3
  syncfusion_flutter_datepicker: ^26.2.9
  google_maps_flutter: ^2.7.0
  geolocator: ^12.0.0
  expandable_bottom_sheet: ^1.1.1+1
  flutter_animarker: ^3.2.0
  file_picker: ^8.0.3
  readmore: ^3.0.0
  url_launcher: ^6.3.0
  flutter_html: ^3.0.0-beta.2
  flutter_widget_from_html_core: ^0.15.1
  flutter_rating_bar: ^4.0.1
  vibration: ^1.9.0
  shimmer: ^3.0.0
  expandable: ^5.0.1
  appinio_swiper: ^2.1.1
  pin_code_fields: ^8.0.1
  fl_chart: ^0.68.0
  custom_map_markers: ^0.0.2+1
  flutter_polyline_points: ^2.0.0
  path: ^1.9.0
  flutter_spinkit: ^5.2.1
  location: ^7.0.0
  modal_bottom_sheet: ^3.0.0
  flutter_typeahead: ^5.2.0
  permission_handler: ^11.3.1
  web_socket_channel: ^2.4.5
  flutter_inappwebview: ^6.0.0
  fluttertoast: ^8.2.6
  flutter_slidable: ^3.1.0
  sliding_up_panel: ^2.0.0+1
  screenshot: ^3.0.0
  flutter_animated_button: ^2.0.3
  audioplayers: ^6.0.0
  card_swiper: ^3.0.1
  dropdown_button2: ^2.3.9
  lottie: ^3.1.2
  app_settings: ^5.1.1
  showcaseview: ^3.0.0
  dart_pusher_channels: ^1.2.2+1
  just_the_tooltip: ^0.0.12
  firebase_crashlytics: ^4.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/language/
    - assets/svg/
    - assets/map/
    - assets/

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/font/sf-pro-text-light.ttf
          weight: 300
        - asset: assets/font/sf-pro-text-regular.ttf
          weight: 400
        - asset: assets/font/sf-pro-text-medium.ttf
          weight: 500
        - asset: assets/font/sf-pro-text-semibold.ttf
          weight: 600
        - asset: assets/font/sf-pro-text-bold.ttf
          weight: 700
        - asset: assets/font/sf-pro-text-heavy.ttf
          weight: 900
