// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkmerbBtGzwyNYjLAUFKPjLqvU474f8Sw',
    appId: '1:822457566949:web:b3c59ece6da4fb74caf60c',
    messagingSenderId: '822457566949',
    projectId: 'awa-vtc-driver',
    authDomain: 'awa-vtc-driver.firebaseapp.com',
    databaseURL: 'https://awa-vtc-driver-default-rtdb.firebaseio.com',
    storageBucket: 'awa-vtc-driver.appspot.com',
    measurementId: 'G-TWXYY1RVNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvnXU6BWbqqnPsdzoMp4JP0nBaZvGlIJk',
    appId: '1:822457566949:web:b3c59ece6da4fb74caf60c',
    messagingSenderId: '822457566949',
    projectId: 'awa-vtc-driver',
    databaseURL: 'https://awa-vtc-driver-default-rtdb.firebaseio.com',
    storageBucket: 'awa-vtc-driver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1T-XvOcssuhrsNF6gi_xp_nsgFm7qVHY',
    appId: '1:822457566949:ios:75c925407794d0c3caf60c',
    messagingSenderId: '822457566949',
    projectId: 'awa-vtc-driver',
    databaseURL: 'https://awa-vtc-driver-default-rtdb.firebaseio.com',
    storageBucket: 'awa-vtc-driver.appspot.com',
    androidClientId: '822457566949-tneoqjbhbb7bomiuq8blpjqujnmadfri.apps.googleusercontent.com',
    iosClientId: '822457566949-ot4j45orugeldag50t19vpdhn4vq4oju.apps.googleusercontent.com',
    iosBundleId: 'com.awavtc.awadriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1T-XvOcssuhrsNF6gi_xp_nsgFm7qVHY',
    appId: '1:822457566949:ios:75c925407794d0c3caf60c',
    messagingSenderId: '822457566949',
    projectId: 'awa-vtc-driver',
    databaseURL: 'https://awa-vtc-driver-default-rtdb.firebaseio.com',
    storageBucket: 'awa-vtc-driver.appspot.com',
    androidClientId: '822457566949-tneoqjbhbb7bomiuq8blpjqujnmadfri.apps.googleusercontent.com',
    iosClientId: '822457566949-ot4j45orugeldag50t19vpdhn4vq4oju.apps.googleusercontent.com',
    iosBundleId: 'com.awavtc.awadriver',
  );
}
